"""add_india_schema_fields

Revision ID: 5eb70655ed3a
Revises: a1b2c3d4e5f6
Create Date: 2026-08-18 14:32:23.426264

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5eb70655ed3a"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("promo_type", sa.String(length=30), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("discount_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("budget_inr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("redemption_count", sa.Integer(), nullable=True),
        sa.Column("sales_lift_percent", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "forecasts",
        sa.Column("product_sku", sa.String(), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("predicted_demand", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("recommended_reorder_qty", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("product_sku", "forecast_date", "horizon_days"),
    )
    op.create_table(
        "inventory_batches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_sku", sa.String(), nullable=True),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("batch_number", sa.String(length=30), nullable=False),
        sa.Column("manufacturing_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("quantity_on_hand", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_sku"],
            ["products.sku"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_sku", sa.String(), nullable=True),
        sa.Column("old_price_inr", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("new_price_inr", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("reason", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "warehouse_transfers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_sku", sa.String(), nullable=True),
        sa.Column("from_warehouse_id", sa.Integer(), nullable=True),
        sa.Column("to_warehouse_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_warehouse_id"],
            ["warehouses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_sku"],
            ["products.sku"],
        ),
        sa.ForeignKeyConstraint(
            ["to_warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventory_adjustments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_sku", sa.String(), nullable=True),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=30), nullable=True),
        sa.Column("adjustment_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["inventory_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_sku"],
            ["products.sku"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "returns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sale_id", sa.Integer(), nullable=True),
        sa.Column("product_sku", sa.String(), nullable=True),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=30), nullable=True),
        sa.Column("return_date", sa.DateTime(), nullable=True),
        sa.Column("refund_amount_inr", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_sku"],
            ["products.sku"],
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales_transactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "categories", sa.Column("gst_percent", sa.Numeric(precision=4, scale=2), nullable=True)
    )
    op.add_column(
        "categories",
        sa.Column("typical_margin_low", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "categories",
        sa.Column("typical_margin_high", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "categories",
        sa.Column("cost_range_low_inr", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "categories",
        sa.Column("cost_range_high_inr", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column("customers", sa.Column("segment", sa.String(length=20), nullable=True))
    op.add_column("customers", sa.Column("city", sa.String(length=60), nullable=True))
    op.add_column("customers", sa.Column("preferred_category_id", sa.Integer(), nullable=True))
    op.add_column(
        "customers", sa.Column("loyalty_score", sa.Numeric(precision=4, scale=2), nullable=True)
    )
    op.add_column(
        "customers",
        sa.Column("lifetime_value_inr", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "customers",
        sa.Column("purchase_frequency", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "customers", sa.Column("avg_basket_inr", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.create_foreign_key(None, "customers", "categories", ["preferred_category_id"], ["id"])
    op.add_column("products", sa.Column("barcode", sa.String(length=13), nullable=True))
    op.add_column("products", sa.Column("name", sa.String(length=160), nullable=True))
    op.add_column(
        "products", sa.Column("gst_percent", sa.Numeric(precision=4, scale=2), nullable=True)
    )
    op.add_column("products", sa.Column("hsn_code", sa.String(length=8), nullable=True))
    op.add_column("products", sa.Column("shelf_life_days", sa.Integer(), nullable=True))
    op.add_column(
        "products", sa.Column("weight_grams", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column("products", sa.Column("reorder_quantity", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("eoq", sa.Integer(), nullable=True))
    op.add_column("products", sa.Column("abc_class", sa.String(length=1), nullable=True))
    op.add_column("products", sa.Column("xyz_class", sa.String(length=1), nullable=True))
    op.add_column("products", sa.Column("behavior_pattern", sa.String(length=20), nullable=True))
    op.add_column("products", sa.Column("active", sa.Boolean(), nullable=True))
    op.alter_column(
        "products",
        "sale_price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="derived: backfilled from the SKU's average observed sales_transactions.unit_price (docs/BUILD.md Backend Module 2); user-editable going forward via PUT /products/{sku}",
        existing_nullable=True,
    )
    op.create_unique_constraint(None, "products", ["barcode"])
    op.add_column("suppliers", sa.Column("city", sa.String(length=60), nullable=True))
    op.add_column("suppliers", sa.Column("state", sa.String(length=40), nullable=True))
    op.add_column("suppliers", sa.Column("pin_code", sa.String(length=6), nullable=True))
    op.add_column("suppliers", sa.Column("contact_person", sa.String(length=100), nullable=True))
    op.add_column("suppliers", sa.Column("mobile", sa.String(length=15), nullable=True))
    op.add_column("suppliers", sa.Column("contact_email", sa.String(length=160), nullable=True))
    op.add_column("suppliers", sa.Column("gstin", sa.String(length=15), nullable=True))
    op.add_column("suppliers", sa.Column("pan", sa.String(length=10), nullable=True))
    op.add_column("suppliers", sa.Column("udyam_number", sa.String(length=20), nullable=True))
    op.add_column("suppliers", sa.Column("fssai_license", sa.String(length=20), nullable=True))
    op.add_column(
        "suppliers", sa.Column("avg_delay_days", sa.Numeric(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "suppliers", sa.Column("on_time_percent", sa.Numeric(precision=5, scale=2), nullable=True)
    )
    op.add_column(
        "suppliers",
        sa.Column("partial_shipment_percent", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "suppliers", sa.Column("cancelled_percent", sa.Numeric(precision=5, scale=2), nullable=True)
    )
    op.add_column("suppliers", sa.Column("payment_terms", sa.String(length=20), nullable=True))
    op.add_column("suppliers", sa.Column("credit_days", sa.Integer(), nullable=True))
    op.add_column("suppliers", sa.Column("moq", sa.Integer(), nullable=True))
    op.add_column("suppliers", sa.Column("preferred_supplier", sa.Boolean(), nullable=True))
    op.add_column("warehouses", sa.Column("location", sa.String(length=160), nullable=True))
    op.add_column("warehouses", sa.Column("state", sa.String(length=40), nullable=True))
    op.add_column("warehouses", sa.Column("zone", sa.String(length=20), nullable=True))
    op.add_column("warehouses", sa.Column("pin_code", sa.String(length=6), nullable=True))
    op.add_column(
        "warehouses", sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True)
    )
    op.add_column(
        "warehouses", sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True)
    )
    op.add_column("warehouses", sa.Column("capacity_units", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("warehouses", "capacity_units")
    op.drop_column("warehouses", "longitude")
    op.drop_column("warehouses", "latitude")
    op.drop_column("warehouses", "pin_code")
    op.drop_column("warehouses", "zone")
    op.drop_column("warehouses", "state")
    op.drop_column("warehouses", "location")
    op.drop_column("suppliers", "preferred_supplier")
    op.drop_column("suppliers", "moq")
    op.drop_column("suppliers", "credit_days")
    op.drop_column("suppliers", "payment_terms")
    op.drop_column("suppliers", "cancelled_percent")
    op.drop_column("suppliers", "partial_shipment_percent")
    op.drop_column("suppliers", "on_time_percent")
    op.drop_column("suppliers", "avg_delay_days")
    op.drop_column("suppliers", "fssai_license")
    op.drop_column("suppliers", "udyam_number")
    op.drop_column("suppliers", "pan")
    op.drop_column("suppliers", "gstin")
    op.drop_column("suppliers", "contact_email")
    op.drop_column("suppliers", "mobile")
    op.drop_column("suppliers", "contact_person")
    op.drop_column("suppliers", "pin_code")
    op.drop_column("suppliers", "state")
    op.drop_column("suppliers", "city")
    op.drop_constraint(None, "products", type_="unique")
    op.alter_column(
        "products",
        "sale_price",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment=None,
        existing_comment="derived: backfilled from the SKU's average observed sales_transactions.unit_price (docs/BUILD.md Backend Module 2); user-editable going forward via PUT /products/{sku}",
        existing_nullable=True,
    )
    op.drop_column("products", "active")
    op.drop_column("products", "behavior_pattern")
    op.drop_column("products", "xyz_class")
    op.drop_column("products", "abc_class")
    op.drop_column("products", "eoq")
    op.drop_column("products", "reorder_quantity")
    op.drop_column("products", "weight_grams")
    op.drop_column("products", "shelf_life_days")
    op.drop_column("products", "hsn_code")
    op.drop_column("products", "gst_percent")
    op.drop_column("products", "name")
    op.drop_column("products", "barcode")
    op.drop_constraint(None, "customers", type_="foreignkey")
    op.drop_column("customers", "avg_basket_inr")
    op.drop_column("customers", "purchase_frequency")
    op.drop_column("customers", "lifetime_value_inr")
    op.drop_column("customers", "loyalty_score")
    op.drop_column("customers", "preferred_category_id")
    op.drop_column("customers", "city")
    op.drop_column("customers", "segment")
    op.drop_column("categories", "cost_range_high_inr")
    op.drop_column("categories", "cost_range_low_inr")
    op.drop_column("categories", "typical_margin_high")
    op.drop_column("categories", "typical_margin_low")
    op.drop_column("categories", "gst_percent")
    op.drop_table("returns")
    op.drop_table("inventory_adjustments")
    op.drop_table("warehouse_transfers")
    op.drop_table("price_history")
    op.drop_table("inventory_batches")
    op.drop_table("forecasts")
    op.drop_table("promotions")
    # ### end Alembic commands ###
