"""add is_read_only to users

Revision ID: 8934e5aa361e
Revises: bfc51c86eec8
Create Date: 2026-07-28 23:34:10.029991

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8934e5aa361e"
down_revision: str | Sequence[str] | None = "bfc51c86eec8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_read_only", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_read_only")
    # ### end Alembic commands ###
