"""initial schema

Revision ID: bfc51c86eec8
Revises: 5e150b7ad8b2
Create Date: 2026-07-28 17:01:38.078788

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfc51c86eec8"
down_revision: str | Sequence[str] | None = "5e150b7ad8b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="derived: data-derivation.md#category-clustering",
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "suppliers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="derived: data-derivation.md#supplier-assignment",
        ),
        sa.Column(
            "lead_time_days",
            sa.Integer(),
            nullable=False,
            comment="derived: data-derivation.md#supplier-assignment",
        ),
        sa.Column(
            "reliability_score",
            sa.Float(),
            nullable=False,
            comment="derived: data-derivation.md#supplier-assignment",
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "products",
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=True,
            comment="derived: data-derivation.md#category-clustering",
        ),
        sa.Column(
            "supplier_id",
            sa.Integer(),
            nullable=True,
            comment="derived: data-derivation.md#supplier-assignment",
        ),
        sa.Column(
            "unit_cost",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="derived: data-derivation.md#cost-price",
        ),
        sa.Column(
            "reorder_point",
            sa.Integer(),
            nullable=True,
            comment="derived: data-derivation.md#reorder-point",
        ),
        sa.Column(
            "safety_stock",
            sa.Integer(),
            nullable=True,
            comment="derived: data-derivation.md#reorder-point",
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("sku"),
    )
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column(
            "order_date",
            sa.Date(),
            nullable=False,
            comment="derived: data-derivation.md#stock-ledger",
        ),
        sa.Column(
            "quantity",
            sa.Integer(),
            nullable=False,
            comment="derived: data-derivation.md#stock-ledger",
        ),
        sa.Column(
            "expected_arrival_date",
            sa.Date(),
            nullable=False,
            comment="derived: data-derivation.md#stock-ledger",
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.CheckConstraint("status IN ('received')", name="ck_purchase_orders_status"),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_purchase_orders_sku", "purchase_orders", ["sku"], unique=False)
    op.create_index(
        "ix_purchase_orders_supplier_id", "purchase_orders", ["supplier_id"], unique=False
    )
    op.create_table(
        "sales_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("invoice", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("invoice_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sales_transactions_invoice"), "sales_transactions", ["invoice"], unique=False
    )
    op.create_index(
        op.f("ix_sales_transactions_invoice_date"),
        "sales_transactions",
        ["invoice_date"],
        unique=False,
    )
    op.create_index(op.f("ix_sales_transactions_sku"), "sales_transactions", ["sku"], unique=False)
    op.create_index(
        "ix_sales_transactions_sku_invoice_date",
        "sales_transactions",
        ["sku", "invoice_date"],
        unique=False,
    )
    op.create_table(
        "stock_levels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column(
            "quantity_on_hand",
            sa.Integer(),
            nullable=False,
            comment="derived: data-derivation.md#stock-ledger",
        ),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku", "as_of_date", name="uq_stock_levels_sku_as_of_date"),
    )
    op.create_index(
        "ix_stock_levels_sku_as_of_date", "stock_levels", ["sku", "as_of_date"], unique=False
    )
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("movement_date", sa.DateTime(), nullable=False),
        sa.Column(
            "quantity_delta",
            sa.Integer(),
            nullable=False,
            comment="derived: data-derivation.md#stock-ledger",
        ),
        sa.Column("movement_type", sa.String(), nullable=False),
        sa.Column("reference", sa.String(), nullable=True),
        sa.Column(
            "provenance",
            sa.String(),
            nullable=False,
            comment="derived: data-derivation.md#stock-ledger",
        ),
        sa.CheckConstraint(
            "movement_type IN ('sale', 'purchase_order', 'opening_balance')",
            name="ck_stock_movements_movement_type",
        ),
        sa.CheckConstraint(
            "provenance IN ('observed', 'derived')", name="ck_stock_movements_provenance"
        ),
        sa.ForeignKeyConstraint(
            ["sku"],
            ["products.sku"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_stock_movements_sku_movement_date",
        "stock_movements",
        ["sku", "movement_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_movements_sku_movement_date", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index("ix_stock_levels_sku_as_of_date", table_name="stock_levels")
    op.drop_table("stock_levels")
    op.drop_index("ix_sales_transactions_sku_invoice_date", table_name="sales_transactions")
    op.drop_index(op.f("ix_sales_transactions_sku"), table_name="sales_transactions")
    op.drop_index(op.f("ix_sales_transactions_invoice_date"), table_name="sales_transactions")
    op.drop_index(op.f("ix_sales_transactions_invoice"), table_name="sales_transactions")
    op.drop_table("sales_transactions")
    op.drop_index("ix_purchase_orders_supplier_id", table_name="purchase_orders")
    op.drop_index("ix_purchase_orders_sku", table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_table("products")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("suppliers")
    op.drop_table("categories")
    # ### end Alembic commands ###
