"""drop_movement_type_constraint

Revision ID: c80c9cae5095
Revises: 5eb70655ed3a
Create Date: 2026-08-18 14:37:37.108712

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c80c9cae5095"
down_revision: str | Sequence[str] | None = "5eb70655ed3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
