"""agent_steps provider column

Revision ID: 690cc23d7f69
Revises: 3a206781ae86
Create Date: 2026-07-30 16:52:00.804803

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "690cc23d7f69"
down_revision: str | Sequence[str] | None = "3a206781ae86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_steps", sa.Column("provider", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_steps", "provider")
    # ### end Alembic commands ###
