import type { Metadata } from "next";
import { Suspense } from "react";
import { RecommendationsContent } from "./RecommendationsContent";

export const metadata: Metadata = {
  title: "AI Recommendations — StockPilot",
  description:
    "Review and act on inventory and supply-chain recommendations generated by RetailOps AI Copilot.",
};

export default function RecommendationsPage() {
  return (
    <Suspense fallback={null}>
      <RecommendationsContent />
    </Suspense>
  );
}
