"use client";

import { useEffect, useState } from "react";
import { RecommendationCard, type Recommendation } from "../../../components/ui/RecommendationCard";
import { getToken } from "../../../lib/auth/token";

const AI_BASE_URL = process.env.NEXT_PUBLIC_AI_BASE_URL || "https://retailops-ai.onrender.com";

type FilterPriority = "all" | Recommendation["priority"];
type FilterStatus = "all" | "pending" | "actioned";

export function RecommendationsContent() {
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filterPriority, setFilterPriority] = useState<FilterPriority>("all");
  const [filterStatus, setFilterStatus] = useState<FilterStatus>("all");

  useEffect(() => {
    let cancelled = false;
    const token = getToken();

    if (!token) {
      Promise.resolve().then(() => {
        if (!cancelled) {
          setError("Please log in to view AI recommendations.");
          setIsLoading(false);
        }
      });
      return;
    }


    fetch(`${AI_BASE_URL}/recommendations`, {
      headers: {
        Accept: "application/json",
        Authorization: `Bearer ${token}`,
      },
    })
      .then(async (response) => {
        if (!response.ok) {
          throw new Error(`Failed to load recommendations: ${response.status}`);
        }
        return response.json() as Promise<Recommendation[]>;
      })
      .then((data) => {
        if (cancelled) return;
        setRecommendations(data);
        setIsLoading(false);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "Could not fetch recommendations.");
        setIsLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  async function handleDecision(id: string, decision: "accept" | "reject" | "snooze", timestamp: string) {
    const token = getToken();
    if (!token) {
      alert("Authentication token expired. Please log in again.");
      return;
    }

    const backendStatus = decision === "accept" ? "accepted" : decision === "reject" ? "rejected" : "snoozed";

    try {
      const response = await fetch(`${AI_BASE_URL}/recommendations/${id}/action`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
          Accept: "application/json",
        },
        body: JSON.stringify({
          status: backendStatus,
          note: `Actioned at ${timestamp}`,
        }),
      });

      if (!response.ok) {
        throw new Error(`Action failed with status ${response.status}`);
      }

      // Update state locally
      setRecommendations((current) =>
        current.map((rec) =>
          rec.id === id ? { ...rec, status: backendStatus } : rec,
        ),
      );
    } catch (err) {
      alert(err instanceof Error ? err.message : "Failed to record recommendation action.");
    }
  }

  const filtered = recommendations.filter((rec) => {
    const matchesPriority = filterPriority === "all" || rec.priority === filterPriority;
    const matchesStatus =
      filterStatus === "all" ||
      (filterStatus === "pending" && (!rec.status || rec.status === "pending")) ||
      (filterStatus === "actioned" &&
        rec.status &&
        rec.status !== "pending");
    return matchesPriority && matchesStatus;
  });

  const pendingCount = recommendations.filter(
    (r) => !r.status || r.status === "pending",
  ).length;

  const totalRevenueAtRisk = filtered.reduce((sum, r) => sum + r.revenue_at_risk, 0);

  return (
    <div className="flex flex-col gap-6 pt-4">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="text-[20px] font-semibold text-[var(--color-text-high)]">
            AI Recommendations
          </h1>
          <p className="mt-1 text-[13px] text-[var(--color-text-mid)]">
            Actions generated by RetailOps AI Copilot — accept, snooze, or reject each.{" "}
            {!isLoading && (
              <span className="font-semibold text-[var(--color-text-high)]">
                {pendingCount} pending recommendation{pendingCount !== 1 ? "s" : ""}
              </span>
            )}
          </p>
        </div>
        {!isLoading && filtered.length > 0 && (
          <div className="flex shrink-0 flex-col items-end gap-1">
            <span className="text-[11px] text-[var(--color-text-mid)] uppercase tracking-wider">
              Revenue at risk (filtered)
            </span>
            <span className="font-mono text-[20px] font-semibold text-[var(--color-text-high)]" data-numeric>
              {new Intl.NumberFormat("en-IN", {
                style: "currency",
                currency: "INR",
                maximumFractionDigits: 0,
              }).format(totalRevenueAtRisk)}
            </span>
          </div>
        )}
      </div>

      {/* Filters */}
      {!isLoading && recommendations.length > 0 && (
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-1.5">
            <label htmlFor="filter-priority" className="text-xs text-[var(--color-text-mid)]">
              Priority
            </label>
            <select
              id="filter-priority"
              value={filterPriority}
              onChange={(e) => setFilterPriority(e.target.value as FilterPriority)}
              className="rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-2 py-1 text-xs text-[var(--color-text-high)] focus:border-[var(--color-accent)] focus:outline-none"
            >
              <option value="all">All</option>
              <option value="critical">Critical</option>
              <option value="high">High</option>
              <option value="medium">Medium</option>
              <option value="low">Low</option>
            </select>
          </div>
          <div className="flex items-center gap-1.5">
            <label htmlFor="filter-status" className="text-xs text-[var(--color-text-mid)]">
              Status
            </label>
            <select
              id="filter-status"
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value as FilterStatus)}
              className="rounded border border-[var(--color-border)] bg-[var(--color-surface)] px-2 py-1 text-xs text-[var(--color-text-high)] focus:border-[var(--color-accent)] focus:outline-none"
            >
              <option value="all">All</option>
              <option value="pending">Pending</option>
              <option value="actioned">Actioned</option>
            </select>
          </div>
          <span className="ml-auto text-xs text-[var(--color-text-dim)]">
            {filtered.length} of {recommendations.length} shown
          </span>
        </div>
      )}

      {isLoading ? (
        <div className="flex flex-col gap-4">
          <div className="h-24 w-full animate-pulse rounded-lg bg-[var(--color-canvas)]" />
          <div className="h-24 w-full animate-pulse rounded-lg bg-[var(--color-canvas)]" />
        </div>
      ) : error ? (
        <div className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-4 text-xs text-[var(--color-danger)]">
          {error}
        </div>
      ) : recommendations.length === 0 ? (
        <div className="flex flex-col items-center justify-center gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] py-16">
          <p className="text-sm font-medium text-[var(--color-text-high)]">No recommendations available</p>
          <p className="text-xs text-[var(--color-text-mid)]">
            Use the RetailOps AI Copilot sidebar to query inventory or run workflows to generate recommendations.
          </p>
        </div>
      ) : filtered.length === 0 ? (
        <div className="flex flex-col items-center justify-center gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] py-16">
          <p className="text-sm font-medium text-[var(--color-text-high)]">No recommendations match filters</p>
          <p className="text-xs text-[var(--color-text-mid)]">Try adjusting the filters above.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2 xl:grid-cols-3">
          {filtered.map((rec) => (
            <RecommendationCard
              key={rec.id}
              recommendation={rec}
              onDecision={handleDecision}
            />
          ))}
        </div>
      )}
    </div>
  );
}
