# generated by datamodel-codegen:
#   filename:  v1.json
#   timestamp: 2026-07-29T08:29:19+00:00

from __future__ import annotations

from datetime import date, datetime
from typing import Annotated, Any

from pydantic import BaseModel, EmailStr, Field, RootModel, SecretStr


class AbcRow(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    sku: Annotated[str, Field(title="Sku")]
    revenue: Annotated[float, Field(title="Revenue")]
    cumulative_pct: Annotated[float, Field(title="Cumulative Pct")]
    abc_class: Annotated[str, Field(title="Abc Class")]


class GrantType(RootModel[str]):
    root: Annotated[str, Field(pattern="^password$", title="Grant Type")]


class BodyLoginAuthLoginPost(BaseModel):
    grant_type: Annotated[GrantType | None, Field(title="Grant Type")] = None
    username: Annotated[str, Field(title="Username")]
    password: Annotated[SecretStr, Field(title="Password")]
    scope: Annotated[str | None, Field(title="Scope")] = ""
    client_id: Annotated[str | None, Field(title="Client Id")] = None
    client_secret: Annotated[SecretStr | None, Field(title="Client Secret")] = None


class DeadStockItem(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    sku: Annotated[str, Field(title="Sku")]
    description: Annotated[str | None, Field(title="Description")]
    quantity_on_hand: Annotated[int, Field(title="Quantity On Hand")]
    last_movement_date: Annotated[datetime | None, Field(title="Last Movement Date")]
    days_since_movement: Annotated[int | None, Field(title="Days Since Movement")]


class ForecastAccuracy(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    selected_model: Annotated[str, Field(title="Selected Model")]
    training_window_start: Annotated[date, Field(title="Training Window Start")]
    training_window_end: Annotated[date, Field(title="Training Window End")]
    test_window_start: Annotated[date, Field(title="Test Window Start")]
    test_window_end: Annotated[date, Field(title="Test Window End")]
    n_skus_evaluated: Annotated[int, Field(title="N Skus Evaluated")]
    seasonal_naive_mae: Annotated[float, Field(title="Seasonal Naive Mae")]
    seasonal_naive_mape: Annotated[float, Field(title="Seasonal Naive Mape")]
    moving_average_mae: Annotated[float, Field(title="Moving Average Mae")]
    moving_average_mape: Annotated[float, Field(title="Moving Average Mape")]
    gbm_mae: Annotated[float, Field(title="Gbm Mae")]
    gbm_mape: Annotated[float, Field(title="Gbm Mape")]


class ForecastRequest(BaseModel):
    skus: Annotated[list[str], Field(min_length=1, title="Skus")]
    horizon_days: Annotated[int, Field(ge=1, le=90, title="Horizon Days")]


class MovementHistoryEntry(BaseModel):
    """
    One stock_movements row. Carries its own provenance label rather
    than the ProvenanceMixin dict, since sale-driven rows are observed
    while opening-balance / injected-PO rows are derived -- a single
    static label per field couldn't express that per-row split.
    """

    movement_date: Annotated[datetime, Field(title="Movement Date")]
    quantity_delta: Annotated[int, Field(title="Quantity Delta")]
    movement_type: Annotated[str, Field(title="Movement Type")]
    provenance: Annotated[str, Field(title="Provenance")]


class PeriodComparison(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    period1_start: Annotated[date, Field(title="Period1 Start")]
    period1_end: Annotated[date, Field(title="Period1 End")]
    period1_revenue: Annotated[float, Field(title="Period1 Revenue")]
    period1_units: Annotated[int, Field(title="Period1 Units")]
    period1_cost: Annotated[float, Field(title="Period1 Cost")]
    period1_gross_profit: Annotated[float, Field(title="Period1 Gross Profit")]
    period1_margin: Annotated[float | None, Field(title="Period1 Margin")]
    period2_start: Annotated[date, Field(title="Period2 Start")]
    period2_end: Annotated[date, Field(title="Period2 End")]
    period2_revenue: Annotated[float, Field(title="Period2 Revenue")]
    period2_units: Annotated[int, Field(title="Period2 Units")]
    period2_cost: Annotated[float, Field(title="Period2 Cost")]
    period2_gross_profit: Annotated[float, Field(title="Period2 Gross Profit")]
    period2_margin: Annotated[float | None, Field(title="Period2 Margin")]
    revenue_delta: Annotated[float, Field(title="Revenue Delta")]
    revenue_delta_pct: Annotated[float | None, Field(title="Revenue Delta Pct")]
    units_delta: Annotated[int, Field(title="Units Delta")]
    units_delta_pct: Annotated[float | None, Field(title="Units Delta Pct")]
    gross_profit_delta: Annotated[float, Field(title="Gross Profit Delta")]
    gross_profit_delta_pct: Annotated[float | None, Field(title="Gross Profit Delta Pct")]


class ProductCreate(BaseModel):
    sku: Annotated[str, Field(title="Sku")]
    description: Annotated[str | None, Field(title="Description")] = None
    category_id: Annotated[int | None, Field(title="Category Id")] = None
    supplier_id: Annotated[int | None, Field(title="Supplier Id")] = None
    unit_cost: Annotated[float | None, Field(title="Unit Cost")] = None
    reorder_point: Annotated[int | None, Field(title="Reorder Point")] = None
    safety_stock: Annotated[int | None, Field(title="Safety Stock")] = None


class ProductDetail(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    sku: Annotated[str, Field(title="Sku")]
    description: Annotated[str | None, Field(title="Description")]
    category_id: Annotated[int | None, Field(title="Category Id")]
    supplier_id: Annotated[int | None, Field(title="Supplier Id")]
    unit_cost: Annotated[float | None, Field(title="Unit Cost")]
    reorder_point: Annotated[int | None, Field(title="Reorder Point")]
    safety_stock: Annotated[int | None, Field(title="Safety Stock")]
    created_at: Annotated[datetime, Field(title="Created At")]
    quantity_on_hand: Annotated[int | None, Field(title="Quantity On Hand")]
    movement_history: Annotated[list[MovementHistoryEntry], Field(title="Movement History")]


class ProductPerformanceRow(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    sku: Annotated[str, Field(title="Sku")]
    description: Annotated[str | None, Field(title="Description")]
    revenue: Annotated[float, Field(title="Revenue")]
    units: Annotated[int, Field(title="Units")]
    margin: Annotated[float | None, Field(title="Margin")]


class ProductRead(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    sku: Annotated[str, Field(title="Sku")]
    description: Annotated[str | None, Field(title="Description")]
    category_id: Annotated[int | None, Field(title="Category Id")]
    supplier_id: Annotated[int | None, Field(title="Supplier Id")]
    unit_cost: Annotated[float | None, Field(title="Unit Cost")]
    reorder_point: Annotated[int | None, Field(title="Reorder Point")]
    safety_stock: Annotated[int | None, Field(title="Safety Stock")]
    created_at: Annotated[datetime, Field(title="Created At")]


class ProductUpdate(BaseModel):
    description: Annotated[str | None, Field(title="Description")] = None
    category_id: Annotated[int | None, Field(title="Category Id")] = None
    supplier_id: Annotated[int | None, Field(title="Supplier Id")] = None
    unit_cost: Annotated[float | None, Field(title="Unit Cost")] = None
    reorder_point: Annotated[int | None, Field(title="Reorder Point")] = None
    safety_stock: Annotated[int | None, Field(title="Safety Stock")] = None


class ProfitPeriod(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    period: Annotated[str, Field(title="Period")]
    revenue: Annotated[float, Field(title="Revenue")]
    cost: Annotated[float, Field(title="Cost")]
    gross_profit: Annotated[float, Field(title="Gross Profit")]
    margin: Annotated[float | None, Field(title="Margin")]


class RevenuePeriod(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    period: Annotated[str, Field(title="Period")]
    revenue: Annotated[float, Field(title="Revenue")]
    units: Annotated[int, Field(title="Units")]


class SkuForecast(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    sku: Annotated[str, Field(title="Sku")]
    predicted_daily_demand: Annotated[float, Field(title="Predicted Daily Demand")]
    confidence_interval_lower: Annotated[float, Field(title="Confidence Interval Lower")]
    confidence_interval_upper: Annotated[float, Field(title="Confidence Interval Upper")]
    model_used: Annotated[str, Field(title="Model Used")]
    training_window_start: Annotated[date | None, Field(title="Training Window Start")]
    training_window_end: Annotated[date | None, Field(title="Training Window End")]
    data_quality: Annotated[str, Field(title="Data Quality")]


class SlowMoverItem(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    sku: Annotated[str, Field(title="Sku")]
    description: Annotated[str | None, Field(title="Description")]
    quantity_on_hand: Annotated[int, Field(title="Quantity On Hand")]
    units_sold: Annotated[int, Field(title="Units Sold")]
    avg_daily_demand: Annotated[float, Field(title="Avg Daily Demand")]


class StockItem(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    sku: Annotated[str, Field(title="Sku")]
    description: Annotated[str | None, Field(title="Description")]
    category: Annotated[str | None, Field(title="Category")]
    quantity_on_hand: Annotated[int, Field(title="Quantity On Hand")]
    reorder_point: Annotated[int | None, Field(title="Reorder Point")]
    safety_stock: Annotated[int | None, Field(title="Safety Stock")]
    as_of_date: Annotated[date, Field(title="As Of Date")]
    is_low_stock: Annotated[bool, Field(title="Is Low Stock")]


class SupplierCreate(BaseModel):
    name: Annotated[str, Field(title="Name")]
    lead_time_days: Annotated[int, Field(title="Lead Time Days")]
    reliability_score: Annotated[float, Field(title="Reliability Score")]


class SupplierDetail(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    id: Annotated[int, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    lead_time_days: Annotated[int, Field(title="Lead Time Days")]
    reliability_score: Annotated[float, Field(title="Reliability Score")]
    created_at: Annotated[datetime, Field(title="Created At")]
    skus: Annotated[list[str], Field(title="Skus")]


class SupplierRead(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    id: Annotated[int, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    lead_time_days: Annotated[int, Field(title="Lead Time Days")]
    reliability_score: Annotated[float, Field(title="Reliability Score")]
    created_at: Annotated[datetime, Field(title="Created At")]


class SupplierUpdate(BaseModel):
    name: Annotated[str | None, Field(title="Name")] = None
    lead_time_days: Annotated[int | None, Field(title="Lead Time Days")] = None
    reliability_score: Annotated[float | None, Field(title="Reliability Score")] = None


class Token(BaseModel):
    access_token: Annotated[str, Field(title="Access Token")]
    token_type: Annotated[str | None, Field(title="Token Type")] = "bearer"


class TurnoverRow(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    category: Annotated[str | None, Field(title="Category")]
    units_sold: Annotated[int, Field(title="Units Sold")]
    avg_quantity_on_hand: Annotated[float, Field(title="Avg Quantity On Hand")]
    turnover_ratio: Annotated[float | None, Field(title="Turnover Ratio")]


class UserCreate(BaseModel):
    email: Annotated[EmailStr, Field(title="Email")]
    password: Annotated[str, Field(min_length=8, title="Password")]


class UserRead(BaseModel):
    id: Annotated[int, Field(title="Id")]
    email: Annotated[EmailStr, Field(title="Email")]
    is_active: Annotated[bool, Field(title="Is Active")]
    is_read_only: Annotated[bool, Field(title="Is Read Only")]
    created_at: Annotated[datetime, Field(title="Created At")]


class ValidationError(BaseModel):
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]
    input: Annotated[Any | None, Field(title="Input")] = None
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None


class ValuationRow(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    category: Annotated[str | None, Field(title="Category")]
    quantity_on_hand: Annotated[int, Field(title="Quantity On Hand")]
    inventory_value: Annotated[float, Field(title="Inventory Value")]


class HTTPValidationError(BaseModel):
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class InventoryValuation(BaseModel):
    field_provenance: Annotated[dict[str, str], Field(alias="_provenance", title="Provenance")]
    field_derivation_ref: Annotated[
        dict[str, str] | None, Field(alias="_derivation_ref", title="Derivation Ref")
    ] = None
    by_category: Annotated[list[ValuationRow], Field(title="By Category")]
    total_quantity_on_hand: Annotated[int, Field(title="Total Quantity On Hand")]
    total_inventory_value: Annotated[float, Field(title="Total Inventory Value")]
